spring:
  application:
    name: allocations-server
  datasource:
    username: root

registration:
  server:
    endpoint: http://registration-server

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env,health

security:
  oauth2:
    client:
      grant-type: client_credentials