spring:
  application:
    name: timesheets-server
  datasource:
    username: root

registration:
  server:
    endpoint: http://registration-server


management:
  endpoint:
    health:
      show-details: always